<!-- Footer -->
<table width="732" height="64" cellpadding="0" cellspacing="0" border="0">
<tr>
<td>&nbsp;</td>
</tr>
<tr bgcolor="#ffffff">
<td width="732" height="1" bgcolor="#b0b0b0"><img src="./images/pixel.gif" alt="" width="732" height="1" hspace="0" vspace="0" border="0" align="left"></td>
</tr>
<tr>
<td width="732" height="8"><img src="./images/pixel.gif" alt="" width="732" height="8" hspace="0" vspace="0" border="0" align="left"></td>
</tr>
<tr valign="top" align="center" id="text_black_small">
<td>Find a mistake? Please, report to us &mdash; <a href="mailto:admin@company.com?subject=Please, make changes in phonebook" id="mail_link">Admin</a>.
<br><?php echo (date("Y"));?></td>
</tr>
</table>
<!-- /Footer -->

<!-- \\\\ -->
</td>
</tr>
</table>
</body>
</html>